package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.python
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            password("env.GRAZIE_JWT_TOKEN", "%grazie.token%")
        }
        update {
            password("env.GRAZIE_JWT_TOKEN", "credentialsJSON:a9d047e5-e89d-4325-97b8-d9be361af6fc")
        }
        add {
            password("docker.password", "credentialsJSON:d7e770b7-d9b5-49fe-9a6e-6ca39ddd0ce8")
        }
        add {
            param("docker.username", "alex28sh")
        }
    }

    expectSteps {
        python {
            environment = poetry {
            }
            command = module {
                module = "verified_cogen"
                scriptArguments = "--insert-conditions-mode=llm-single-step                     --llm-profile=%llm-profile%                     --bench-types=%bench-types%                     --tries 10                     --runs 5                     --filter-by-ext %extension%                     --output-logging                     --dir %directory%                     --modes=mode1,mode2,mode3,mode4,mode5,mode6                     --prompts-directory=%prompts%"
            }
            dockerImage = "weethet/verified-cogen:latest"
        }
    }
    steps {
        insert(1) {
            dockerCommand {
                id = "DockerCommand"
                commandType = build {
                    source = file {
                        path = "Dockerfile"
                    }
                }
            }
        }
    }
}
