package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            password("env.GRAZIE_JWT_TOKEN", "%grazie.token%")
        }
        update {
            password("env.GRAZIE_JWT_TOKEN", "credentialsJSON:40d05b0a-9c5e-4cd9-a0d7-b91ce83a7806")
        }
        add {
            password("grazie.token", "credentialsJSON:01d25184-666d-4a6d-a9c6-80ac12a976dc")
        }
    }
}
