package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            password("env.GRAZIE_JWT_TOKEN", "%grazie.token%")
        }
        update {
            password("env.GRAZIE_JWT_TOKEN", "credentialsJSON:a9d047e5-e89d-4325-97b8-d9be361af6fc")
        }
    }
}
